// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: citizen.proto

package primtech.citizen;

public final class CitizenOuterClass {
  private CitizenOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AptitudeLevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:primtech.citizen.AptitudeLevel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 aptitude_id = 1;</code>
     * @return The aptitudeId.
     */
    int getAptitudeId();

    /**
     * <code>double level = 2;</code>
     * @return The level.
     */
    double getLevel();
  }
  /**
   * Protobuf type {@code primtech.citizen.AptitudeLevel}
   */
  public static final class AptitudeLevel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:primtech.citizen.AptitudeLevel)
      AptitudeLevelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AptitudeLevel.newBuilder() to construct.
    private AptitudeLevel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AptitudeLevel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AptitudeLevel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AptitudeLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              aptitudeId_ = input.readInt32();
              break;
            }
            case 17: {

              level_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_AptitudeLevel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_AptitudeLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              primtech.citizen.CitizenOuterClass.AptitudeLevel.class, primtech.citizen.CitizenOuterClass.AptitudeLevel.Builder.class);
    }

    public static final int APTITUDE_ID_FIELD_NUMBER = 1;
    private int aptitudeId_;
    /**
     * <code>int32 aptitude_id = 1;</code>
     * @return The aptitudeId.
     */
    @java.lang.Override
    public int getAptitudeId() {
      return aptitudeId_;
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private double level_;
    /**
     * <code>double level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public double getLevel() {
      return level_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (aptitudeId_ != 0) {
        output.writeInt32(1, aptitudeId_);
      }
      if (level_ != 0D) {
        output.writeDouble(2, level_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (aptitudeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, aptitudeId_);
      }
      if (level_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, level_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof primtech.citizen.CitizenOuterClass.AptitudeLevel)) {
        return super.equals(obj);
      }
      primtech.citizen.CitizenOuterClass.AptitudeLevel other = (primtech.citizen.CitizenOuterClass.AptitudeLevel) obj;

      if (getAptitudeId()
          != other.getAptitudeId()) return false;
      if (java.lang.Double.doubleToLongBits(getLevel())
          != java.lang.Double.doubleToLongBits(
              other.getLevel())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APTITUDE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAptitudeId();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLevel()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.AptitudeLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(primtech.citizen.CitizenOuterClass.AptitudeLevel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code primtech.citizen.AptitudeLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:primtech.citizen.AptitudeLevel)
        primtech.citizen.CitizenOuterClass.AptitudeLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_AptitudeLevel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_AptitudeLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                primtech.citizen.CitizenOuterClass.AptitudeLevel.class, primtech.citizen.CitizenOuterClass.AptitudeLevel.Builder.class);
      }

      // Construct using primtech.citizen.CitizenOuterClass.AptitudeLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        aptitudeId_ = 0;

        level_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_AptitudeLevel_descriptor;
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.AptitudeLevel getDefaultInstanceForType() {
        return primtech.citizen.CitizenOuterClass.AptitudeLevel.getDefaultInstance();
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.AptitudeLevel build() {
        primtech.citizen.CitizenOuterClass.AptitudeLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.AptitudeLevel buildPartial() {
        primtech.citizen.CitizenOuterClass.AptitudeLevel result = new primtech.citizen.CitizenOuterClass.AptitudeLevel(this);
        result.aptitudeId_ = aptitudeId_;
        result.level_ = level_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof primtech.citizen.CitizenOuterClass.AptitudeLevel) {
          return mergeFrom((primtech.citizen.CitizenOuterClass.AptitudeLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(primtech.citizen.CitizenOuterClass.AptitudeLevel other) {
        if (other == primtech.citizen.CitizenOuterClass.AptitudeLevel.getDefaultInstance()) return this;
        if (other.getAptitudeId() != 0) {
          setAptitudeId(other.getAptitudeId());
        }
        if (other.getLevel() != 0D) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        primtech.citizen.CitizenOuterClass.AptitudeLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (primtech.citizen.CitizenOuterClass.AptitudeLevel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int aptitudeId_ ;
      /**
       * <code>int32 aptitude_id = 1;</code>
       * @return The aptitudeId.
       */
      @java.lang.Override
      public int getAptitudeId() {
        return aptitudeId_;
      }
      /**
       * <code>int32 aptitude_id = 1;</code>
       * @param value The aptitudeId to set.
       * @return This builder for chaining.
       */
      public Builder setAptitudeId(int value) {
        
        aptitudeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 aptitude_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAptitudeId() {
        
        aptitudeId_ = 0;
        onChanged();
        return this;
      }

      private double level_ ;
      /**
       * <code>double level = 2;</code>
       * @return The level.
       */
      @java.lang.Override
      public double getLevel() {
        return level_;
      }
      /**
       * <code>double level = 2;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(double value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double level = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:primtech.citizen.AptitudeLevel)
    }

    // @@protoc_insertion_point(class_scope:primtech.citizen.AptitudeLevel)
    private static final primtech.citizen.CitizenOuterClass.AptitudeLevel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new primtech.citizen.CitizenOuterClass.AptitudeLevel();
    }

    public static primtech.citizen.CitizenOuterClass.AptitudeLevel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AptitudeLevel>
        PARSER = new com.google.protobuf.AbstractParser<AptitudeLevel>() {
      @java.lang.Override
      public AptitudeLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AptitudeLevel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AptitudeLevel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AptitudeLevel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public primtech.citizen.CitizenOuterClass.AptitudeLevel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SkillLevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:primtech.citizen.SkillLevel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 skill_id = 1;</code>
     * @return The skillId.
     */
    int getSkillId();

    /**
     * <code>double level = 2;</code>
     * @return The level.
     */
    double getLevel();
  }
  /**
   * Protobuf type {@code primtech.citizen.SkillLevel}
   */
  public static final class SkillLevel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:primtech.citizen.SkillLevel)
      SkillLevelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkillLevel.newBuilder() to construct.
    private SkillLevel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkillLevel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SkillLevel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkillLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              skillId_ = input.readInt32();
              break;
            }
            case 17: {

              level_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_SkillLevel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_SkillLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              primtech.citizen.CitizenOuterClass.SkillLevel.class, primtech.citizen.CitizenOuterClass.SkillLevel.Builder.class);
    }

    public static final int SKILL_ID_FIELD_NUMBER = 1;
    private int skillId_;
    /**
     * <code>int32 skill_id = 1;</code>
     * @return The skillId.
     */
    @java.lang.Override
    public int getSkillId() {
      return skillId_;
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private double level_;
    /**
     * <code>double level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public double getLevel() {
      return level_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (skillId_ != 0) {
        output.writeInt32(1, skillId_);
      }
      if (level_ != 0D) {
        output.writeDouble(2, level_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, skillId_);
      }
      if (level_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, level_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof primtech.citizen.CitizenOuterClass.SkillLevel)) {
        return super.equals(obj);
      }
      primtech.citizen.CitizenOuterClass.SkillLevel other = (primtech.citizen.CitizenOuterClass.SkillLevel) obj;

      if (getSkillId()
          != other.getSkillId()) return false;
      if (java.lang.Double.doubleToLongBits(getLevel())
          != java.lang.Double.doubleToLongBits(
              other.getLevel())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKILL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLevel()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.SkillLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(primtech.citizen.CitizenOuterClass.SkillLevel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code primtech.citizen.SkillLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:primtech.citizen.SkillLevel)
        primtech.citizen.CitizenOuterClass.SkillLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_SkillLevel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_SkillLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                primtech.citizen.CitizenOuterClass.SkillLevel.class, primtech.citizen.CitizenOuterClass.SkillLevel.Builder.class);
      }

      // Construct using primtech.citizen.CitizenOuterClass.SkillLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        skillId_ = 0;

        level_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_SkillLevel_descriptor;
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.SkillLevel getDefaultInstanceForType() {
        return primtech.citizen.CitizenOuterClass.SkillLevel.getDefaultInstance();
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.SkillLevel build() {
        primtech.citizen.CitizenOuterClass.SkillLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.SkillLevel buildPartial() {
        primtech.citizen.CitizenOuterClass.SkillLevel result = new primtech.citizen.CitizenOuterClass.SkillLevel(this);
        result.skillId_ = skillId_;
        result.level_ = level_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof primtech.citizen.CitizenOuterClass.SkillLevel) {
          return mergeFrom((primtech.citizen.CitizenOuterClass.SkillLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(primtech.citizen.CitizenOuterClass.SkillLevel other) {
        if (other == primtech.citizen.CitizenOuterClass.SkillLevel.getDefaultInstance()) return this;
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        if (other.getLevel() != 0D) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        primtech.citizen.CitizenOuterClass.SkillLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (primtech.citizen.CitizenOuterClass.SkillLevel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int skillId_ ;
      /**
       * <code>int32 skill_id = 1;</code>
       * @return The skillId.
       */
      @java.lang.Override
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>int32 skill_id = 1;</code>
       * @param value The skillId to set.
       * @return This builder for chaining.
       */
      public Builder setSkillId(int value) {
        
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skill_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkillId() {
        
        skillId_ = 0;
        onChanged();
        return this;
      }

      private double level_ ;
      /**
       * <code>double level = 2;</code>
       * @return The level.
       */
      @java.lang.Override
      public double getLevel() {
        return level_;
      }
      /**
       * <code>double level = 2;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(double value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double level = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:primtech.citizen.SkillLevel)
    }

    // @@protoc_insertion_point(class_scope:primtech.citizen.SkillLevel)
    private static final primtech.citizen.CitizenOuterClass.SkillLevel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new primtech.citizen.CitizenOuterClass.SkillLevel();
    }

    public static primtech.citizen.CitizenOuterClass.SkillLevel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkillLevel>
        PARSER = new com.google.protobuf.AbstractParser<SkillLevel>() {
      @java.lang.Override
      public SkillLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkillLevel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkillLevel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkillLevel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public primtech.citizen.CitizenOuterClass.SkillLevel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CitizenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:primtech.citizen.Citizen)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code primtech.citizen.Citizen}
   */
  public static final class Citizen extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:primtech.citizen.Citizen)
      CitizenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Citizen.newBuilder() to construct.
    private Citizen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Citizen() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Citizen();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Citizen(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_Citizen_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_Citizen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              primtech.citizen.CitizenOuterClass.Citizen.class, primtech.citizen.CitizenOuterClass.Citizen.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof primtech.citizen.CitizenOuterClass.Citizen)) {
        return super.equals(obj);
      }
      primtech.citizen.CitizenOuterClass.Citizen other = (primtech.citizen.CitizenOuterClass.Citizen) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.citizen.CitizenOuterClass.Citizen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(primtech.citizen.CitizenOuterClass.Citizen prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code primtech.citizen.Citizen}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:primtech.citizen.Citizen)
        primtech.citizen.CitizenOuterClass.CitizenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_Citizen_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_Citizen_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                primtech.citizen.CitizenOuterClass.Citizen.class, primtech.citizen.CitizenOuterClass.Citizen.Builder.class);
      }

      // Construct using primtech.citizen.CitizenOuterClass.Citizen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return primtech.citizen.CitizenOuterClass.internal_static_primtech_citizen_Citizen_descriptor;
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.Citizen getDefaultInstanceForType() {
        return primtech.citizen.CitizenOuterClass.Citizen.getDefaultInstance();
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.Citizen build() {
        primtech.citizen.CitizenOuterClass.Citizen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public primtech.citizen.CitizenOuterClass.Citizen buildPartial() {
        primtech.citizen.CitizenOuterClass.Citizen result = new primtech.citizen.CitizenOuterClass.Citizen(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof primtech.citizen.CitizenOuterClass.Citizen) {
          return mergeFrom((primtech.citizen.CitizenOuterClass.Citizen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(primtech.citizen.CitizenOuterClass.Citizen other) {
        if (other == primtech.citizen.CitizenOuterClass.Citizen.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        primtech.citizen.CitizenOuterClass.Citizen parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (primtech.citizen.CitizenOuterClass.Citizen) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:primtech.citizen.Citizen)
    }

    // @@protoc_insertion_point(class_scope:primtech.citizen.Citizen)
    private static final primtech.citizen.CitizenOuterClass.Citizen DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new primtech.citizen.CitizenOuterClass.Citizen();
    }

    public static primtech.citizen.CitizenOuterClass.Citizen getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Citizen>
        PARSER = new com.google.protobuf.AbstractParser<Citizen>() {
      @java.lang.Override
      public Citizen parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Citizen(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Citizen> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Citizen> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public primtech.citizen.CitizenOuterClass.Citizen getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_primtech_citizen_AptitudeLevel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_primtech_citizen_AptitudeLevel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_primtech_citizen_SkillLevel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_primtech_citizen_SkillLevel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_primtech_citizen_Citizen_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_primtech_citizen_Citizen_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcitizen.proto\022\020primtech.citizen\032\rgener" +
      "al.proto\"3\n\rAptitudeLevel\022\023\n\013aptitude_id" +
      "\030\001 \001(\005\022\r\n\005level\030\002 \001(\001\"-\n\nSkillLevel\022\020\n\010s" +
      "kill_id\030\001 \001(\005\022\r\n\005level\030\002 \001(\001\"#\n\007Citizen\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t2K\n\016CitizenServ" +
      "ice\0229\n\nGetCitizen\022\016.primtech.Void\032\031.prim" +
      "tech.citizen.Citizen\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          primtech.General.getDescriptor(),
        });
    internal_static_primtech_citizen_AptitudeLevel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_primtech_citizen_AptitudeLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_primtech_citizen_AptitudeLevel_descriptor,
        new java.lang.String[] { "AptitudeId", "Level", });
    internal_static_primtech_citizen_SkillLevel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_primtech_citizen_SkillLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_primtech_citizen_SkillLevel_descriptor,
        new java.lang.String[] { "SkillId", "Level", });
    internal_static_primtech_citizen_Citizen_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_primtech_citizen_Citizen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_primtech_citizen_Citizen_descriptor,
        new java.lang.String[] { "Id", "Name", });
    primtech.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
