// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package primtech.game;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FrameInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:primtech.game.FrameInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 frame_number = 1;</code>
     * @return The frameNumber.
     */
    long getFrameNumber();

    /**
     * <code>int64 actual_frame_time_nanos = 2;</code>
     * @return The actualFrameTimeNanos.
     */
    long getActualFrameTimeNanos();

    /**
     * <code>int64 target_frame_time_nanos = 3;</code>
     * @return The targetFrameTimeNanos.
     */
    long getTargetFrameTimeNanos();
  }
  /**
   * Protobuf type {@code primtech.game.FrameInfo}
   */
  public static final class FrameInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:primtech.game.FrameInfo)
      FrameInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FrameInfo.newBuilder() to construct.
    private FrameInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FrameInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FrameInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FrameInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              frameNumber_ = input.readInt64();
              break;
            }
            case 16: {

              actualFrameTimeNanos_ = input.readInt64();
              break;
            }
            case 24: {

              targetFrameTimeNanos_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return primtech.game.Game.internal_static_primtech_game_FrameInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return primtech.game.Game.internal_static_primtech_game_FrameInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              primtech.game.Game.FrameInfo.class, primtech.game.Game.FrameInfo.Builder.class);
    }

    public static final int FRAME_NUMBER_FIELD_NUMBER = 1;
    private long frameNumber_;
    /**
     * <code>int64 frame_number = 1;</code>
     * @return The frameNumber.
     */
    @java.lang.Override
    public long getFrameNumber() {
      return frameNumber_;
    }

    public static final int ACTUAL_FRAME_TIME_NANOS_FIELD_NUMBER = 2;
    private long actualFrameTimeNanos_;
    /**
     * <code>int64 actual_frame_time_nanos = 2;</code>
     * @return The actualFrameTimeNanos.
     */
    @java.lang.Override
    public long getActualFrameTimeNanos() {
      return actualFrameTimeNanos_;
    }

    public static final int TARGET_FRAME_TIME_NANOS_FIELD_NUMBER = 3;
    private long targetFrameTimeNanos_;
    /**
     * <code>int64 target_frame_time_nanos = 3;</code>
     * @return The targetFrameTimeNanos.
     */
    @java.lang.Override
    public long getTargetFrameTimeNanos() {
      return targetFrameTimeNanos_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (frameNumber_ != 0L) {
        output.writeInt64(1, frameNumber_);
      }
      if (actualFrameTimeNanos_ != 0L) {
        output.writeInt64(2, actualFrameTimeNanos_);
      }
      if (targetFrameTimeNanos_ != 0L) {
        output.writeInt64(3, targetFrameTimeNanos_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (frameNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, frameNumber_);
      }
      if (actualFrameTimeNanos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, actualFrameTimeNanos_);
      }
      if (targetFrameTimeNanos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, targetFrameTimeNanos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof primtech.game.Game.FrameInfo)) {
        return super.equals(obj);
      }
      primtech.game.Game.FrameInfo other = (primtech.game.Game.FrameInfo) obj;

      if (getFrameNumber()
          != other.getFrameNumber()) return false;
      if (getActualFrameTimeNanos()
          != other.getActualFrameTimeNanos()) return false;
      if (getTargetFrameTimeNanos()
          != other.getTargetFrameTimeNanos()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FRAME_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrameNumber());
      hash = (37 * hash) + ACTUAL_FRAME_TIME_NANOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getActualFrameTimeNanos());
      hash = (37 * hash) + TARGET_FRAME_TIME_NANOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetFrameTimeNanos());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static primtech.game.Game.FrameInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.game.Game.FrameInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static primtech.game.Game.FrameInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.game.Game.FrameInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static primtech.game.Game.FrameInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static primtech.game.Game.FrameInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(primtech.game.Game.FrameInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code primtech.game.FrameInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:primtech.game.FrameInfo)
        primtech.game.Game.FrameInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return primtech.game.Game.internal_static_primtech_game_FrameInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return primtech.game.Game.internal_static_primtech_game_FrameInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                primtech.game.Game.FrameInfo.class, primtech.game.Game.FrameInfo.Builder.class);
      }

      // Construct using primtech.game.Game.FrameInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        frameNumber_ = 0L;

        actualFrameTimeNanos_ = 0L;

        targetFrameTimeNanos_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return primtech.game.Game.internal_static_primtech_game_FrameInfo_descriptor;
      }

      @java.lang.Override
      public primtech.game.Game.FrameInfo getDefaultInstanceForType() {
        return primtech.game.Game.FrameInfo.getDefaultInstance();
      }

      @java.lang.Override
      public primtech.game.Game.FrameInfo build() {
        primtech.game.Game.FrameInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public primtech.game.Game.FrameInfo buildPartial() {
        primtech.game.Game.FrameInfo result = new primtech.game.Game.FrameInfo(this);
        result.frameNumber_ = frameNumber_;
        result.actualFrameTimeNanos_ = actualFrameTimeNanos_;
        result.targetFrameTimeNanos_ = targetFrameTimeNanos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof primtech.game.Game.FrameInfo) {
          return mergeFrom((primtech.game.Game.FrameInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(primtech.game.Game.FrameInfo other) {
        if (other == primtech.game.Game.FrameInfo.getDefaultInstance()) return this;
        if (other.getFrameNumber() != 0L) {
          setFrameNumber(other.getFrameNumber());
        }
        if (other.getActualFrameTimeNanos() != 0L) {
          setActualFrameTimeNanos(other.getActualFrameTimeNanos());
        }
        if (other.getTargetFrameTimeNanos() != 0L) {
          setTargetFrameTimeNanos(other.getTargetFrameTimeNanos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        primtech.game.Game.FrameInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (primtech.game.Game.FrameInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long frameNumber_ ;
      /**
       * <code>int64 frame_number = 1;</code>
       * @return The frameNumber.
       */
      @java.lang.Override
      public long getFrameNumber() {
        return frameNumber_;
      }
      /**
       * <code>int64 frame_number = 1;</code>
       * @param value The frameNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFrameNumber(long value) {
        
        frameNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 frame_number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameNumber() {
        
        frameNumber_ = 0L;
        onChanged();
        return this;
      }

      private long actualFrameTimeNanos_ ;
      /**
       * <code>int64 actual_frame_time_nanos = 2;</code>
       * @return The actualFrameTimeNanos.
       */
      @java.lang.Override
      public long getActualFrameTimeNanos() {
        return actualFrameTimeNanos_;
      }
      /**
       * <code>int64 actual_frame_time_nanos = 2;</code>
       * @param value The actualFrameTimeNanos to set.
       * @return This builder for chaining.
       */
      public Builder setActualFrameTimeNanos(long value) {
        
        actualFrameTimeNanos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 actual_frame_time_nanos = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearActualFrameTimeNanos() {
        
        actualFrameTimeNanos_ = 0L;
        onChanged();
        return this;
      }

      private long targetFrameTimeNanos_ ;
      /**
       * <code>int64 target_frame_time_nanos = 3;</code>
       * @return The targetFrameTimeNanos.
       */
      @java.lang.Override
      public long getTargetFrameTimeNanos() {
        return targetFrameTimeNanos_;
      }
      /**
       * <code>int64 target_frame_time_nanos = 3;</code>
       * @param value The targetFrameTimeNanos to set.
       * @return This builder for chaining.
       */
      public Builder setTargetFrameTimeNanos(long value) {
        
        targetFrameTimeNanos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 target_frame_time_nanos = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetFrameTimeNanos() {
        
        targetFrameTimeNanos_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:primtech.game.FrameInfo)
    }

    // @@protoc_insertion_point(class_scope:primtech.game.FrameInfo)
    private static final primtech.game.Game.FrameInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new primtech.game.Game.FrameInfo();
    }

    public static primtech.game.Game.FrameInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FrameInfo>
        PARSER = new com.google.protobuf.AbstractParser<FrameInfo>() {
      @java.lang.Override
      public FrameInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FrameInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FrameInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FrameInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public primtech.game.Game.FrameInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_primtech_game_FrameInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_primtech_game_FrameInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\rprimtech.game\032\rgeneral.pro" +
      "to\"c\n\tFrameInfo\022\024\n\014frame_number\030\001 \001(\003\022\037\n" +
      "\027actual_frame_time_nanos\030\002 \001(\003\022\037\n\027target" +
      "_frame_time_nanos\030\003 \001(\0032K\n\013GameService\022<" +
      "\n\014StreamFrames\022\016.primtech.Void\032\030.primtec" +
      "h.game.FrameInfo\"\0000\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          primtech.General.getDescriptor(),
        });
    internal_static_primtech_game_FrameInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_primtech_game_FrameInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_primtech_game_FrameInfo_descriptor,
        new java.lang.String[] { "FrameNumber", "ActualFrameTimeNanos", "TargetFrameTimeNanos", });
    primtech.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
